### ISSUE TITLE
Upgrade the cosmos-sdk version to v0.50.7

### ISSUE THREAD

**Issue by shivhg** [Reecepbcups/cosmos-submit-tx-client#3]
The current code is not usable for latest version of cosmos, even the cosmos docs is outdated. Can you please update this to latest version of cosmos please

**Comment by reecepbcups** [comment]
Sure :)

**Comment by reecepbcups** [comment]
Works now for v0.50

I tested with my POA module & added this line to the test_node.sh

`  BINARY genesis add-genesis-account cosmos12jz2v5psq5hu4px9ld23uztzek8y0xmzdxuheh 1000000stake,1000000utest --keyring-backend $KEYRING`

All signing works as expected now
![image](https://github.com/user-attachments/assets/90a7f933-a8aa-4a2a-a22b-9c6dd8d8276b)
